### ISSUE TITLE
Docker build fails due to missing GLIBC_2.29

### ISSUE THREAD

**Issue by ozyx** [yamcs/quickstart#40]
Looks like the addition of the RocksDB merge operator feature for YAMCS 5.10 has made it incompatible with the [base image](https://hub.docker.com/layers/library/maven/3.8.5-openjdk-17/images/sha256-62e6a9e10fb57f3019adeea481339c999930e7363f2468d1f51a7c0be4bca26d?context=explore) used by `maven:openjdk-17/18`, which provides glibc v2.28

```
2024-09-09 10:54:12 Exception in thread "main" 17:54:12.322 _global [1] stdout java.lang.UnsatisfiedLinkError: /tmp/librocksdbjni17992035822257415058.so: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/librocksdbjni17992035822257415058.so)
2024-09-09 10:54:12 17:54:12.322 _global [1] stdout     at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
2024-09-09 10:54:12 17:54:12.322 _global [1] stdout     at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:395)
2024-09-09 10:54:12 17:54:12.322 _global [1] stdout     at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:234)
2024-09-09 10:54:12 17:54:12.322 _global [1] stdout     at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:176)
2024-09-09 10:54:12 17:54:12.322 _global [1] stdout     at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2394)
2024-09-09 10:54:12 17:54:12.323 _global [1] stdout     at java.base/java.lang.Runtime.load0(Runtime.java:785)
2024-09-09 10:54:12 17:54:12.323 _global [1] stdout     at java.base/java.lang.System.load(System.java:1979)
2024-09-09 10:54:12 17:54:12.323 _global [1] stdout     at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:107)
2024-09-09 10:54:12 17:54:12.323 _global [1] stdout     at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:87)
2024-09-09 10:54:12 17:54:12.323 _global [1] stdout     at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:73)
2024-09-09 10:54:12 17:54:12.323 _global [1] stdout     at org.rocksdb.FlushOptions.newFlushOptionsInance(FlushOptions.java:77)
2024-09-09 10:54:12 17:54:12.323 _global [1] stdout     at org.rocksdb.FlushOptions.<init>(FlushOptions.java:17)
2024-09-09 10:54:12 17:54:12.324 _global [1] stdout     at org.yamcs.yarch.rocksdb.RDBFactory.<clinit>(RDBFactory.java:44)
2024-09-09 10:54:12 17:54:12.324 _global [1] stdout     at org.yamcs.YamcsServer.prepareStart(YamcsServer.java:1199)
2024-09-09 10:54:12 17:54:12.324 _global [1] stdout     at org.yamcs.YamcsServer.main(YamcsServer.java:991)
```

**Comment by fqqb** [comment]
True, pushed a commit that should fix it.

**Comment by ozyx** [comment]
@fqqb Awesome-- looks like it builds successfully with that image.

Thanks for the quick fix, Fabian! Cheers.
